Repository jenkins-x/environment-tekton-mole-dev, pull requests merged in 2019-07, with the labels that each got.

#199 chore: lets switch tekton to using gcs rather than PVs to test parallel builds
  env/templates/tekton-cm.yaml
Labels: approved, size/XS

#200 chore: remove sleep used for debugging
  jenkins-x.yml
Labels: approved, size/XS

#201 chore: fix gc previews and deisable broken monocular
  env/values.yaml
Labels: approved, size/S

#202 fix: gcs location prefix for tekton builds
  env/templates/tekton-cm.yaml
Labels: approved, size/XS

#204 chore: revert back to PV for tekton until this is in prod https://github.com/tektoncd/pipeline/issues/1047
  env/templates/tekton-cm.yaml
Labels: approved, lgtm, size/XS

#198 chore: Add e2e gc cronjob to env repo
  env/templates/e2e-gc-cj.yaml
Labels: approved, lgtm, size/M

#208 fix: update builder image fopr step apply to get fix for logging using gh pages
  jenkins-x.yml
Labels: approved, lgtm, size/XS

#213 fix: reduce stackdriver metrics and remove our prometheus app
  env/jx-app-prometheus/README.MD
  env/jx-app-prometheus/templates/jx-app-prometheus-app.yaml
  env/requirements.yaml
Labels: approved, size/S

#215 fix: Upgrade e2e-gc to pick up fix to SA cleanup
  env/templates/e2e-gc-cj.yaml
Labels: approved, lgtm, size/XS

#216 fix: upgrade builder image to get latest SA clean up script
  env/templates/e2e-gc-cj.yaml
Labels: approved, lgtm, size/XS

#218 fix: Use newer image in pipelinerunner and controllerbuild
  env/prow/values.yaml
Labels: approved, lgtm, size/XS

#220 fix: newer pipelinerunner also needed newer tekton, so sigh roll back
  env/prow/values.yaml
Labels: approved, lgtm, size/XS

#226 fix: increasing pipelinerunner max memory limit
  env/prow/values.yaml
Labels: approved, lgtm, size/XS
