Repository jenkins-x/environment-tekton-mole-dev, pull requests merged in 2019-06, with the labels that each got.

#168 manually override buildcontroller until we can upgrade platform again
  env/values.yaml
Labels: approved, size/XS

#169 increase prometheus PV
  env/values.yaml
Labels: approved, size/XS

#170 use correct values keys
  env/values.yaml
Labels: approved, size/S

#178 Enable build logging in build controller
  env/values.yaml
Labels: approved, size/XS

#179 Enable JSON logs for build controller
  env/values.yaml
Labels: approved, size/XS

#180 chore: updating athens replicas to 2
  env/values.yaml
Labels: approved, size/XS

#185 Chore: update to 0.4.0 of Athens
  env/requirements.yaml
  env/values.yaml
Labels: approved, lgtm, size/XS

#186 add a SA to upload artifacts to a storage bucket
  env/templates/artifact-upload-secret.yaml
Labels: approved, size/XS
