Repository jenkins-x/environment-tekton-mole-dev, pull requests merged in 2019-05, with the labels that each got.

#83 Upgrade prow to v0.0.573
  env/requirements.yaml
Labels: approved, size/XS

#82 Update jx-app-ui to 0.0.9
  env/requirements.yaml
Labels: approved, size/XS

#86 fix: set up long term log storage
  env/templates/dev-env.yaml
Labels: approved, lgtm, size/XS

#87 add npm token secret
  env/templates/npm-secret.yaml
  env/templates/tekton-artifact-bucket-cm.yaml
  env/values.yaml
Labels: approved, size/S

#89 switch npm token to .npmrc style secret
  env/templates/npm-secret.yaml
Labels: approved, size/XS

#90 fix: removed invalid file to fix master build
  env/templates/tekton-artifact-bucket-cm.yaml
Labels: approved, size/XS

#98 set some default resources for prometheus exporter deamonset
  env/values.yaml
Labels: approved, size/S

#100 add a kubernetes service for postgres db
  env/templates/postgres-svc.yaml
  env/values.yaml
Labels: approved, size/S

#116 lets use the right dex
  env/jx-app-sso/values.yaml
Labels: approved, size/XS

#118 manually bump tekton version as its not an app
  env/requirements.yaml
Labels: approved, size/XS

#119 avoid default limit ranges now that Tekton uses containers rather than initcontainers
  env/templates/limits.yaml
Labels: approved, size/S

#120 manually bump prow version as its not an app
  env/prow/values.yaml
  env/requirements.yaml
Labels: approved, size/XS

#123 add missing dex config
  env/jx-app-sso/values.yaml
Labels: approved, size/S

#130 get latest jx so we can work with new vault
  jenkins-x.yml
Labels: approved, size/XS

#131 chore: add template for codecov secret
  env/templates/codecov-secret.yaml
  env/values.yaml
Labels: approved, size/S

#132 feat: add nexus
  env/templates/cb-npm-secret.yaml
  env/values.yaml
Labels: approved, size/S

#133 Chore: fix the syntax
  env/templates/cb-npm-secret.yaml
Labels: approved, size/XS

#134 fix: another syntax
  env/templates/cb-npm-secret.yaml
Labels: approved, size/XS

#135 yet another syntax
  env/templates/cb-npm-secret.yaml
Labels: approved, size/XS

#136 the syntax we normally use is actually only working by chance
  env/templates/cb-npm-secret.yaml
  env/templates/npm-secret.yaml
Labels: approved, size/XS

#149 Add Amazon KMS id for bdd tests
  env/templates/bdd-akms-secret.yaml
  env/values.yaml
Labels: approved, size/S

#153 Add jx-demo-sa secret
  env/templates/jx-demo-sa.yaml
  env/values.yaml
Labels: approved, size/XS

#154 fix: remove the b64enc, did that in vault
  env/templates/jx-demo-sa.yaml
Labels: approved, size/XS
