Repository jenkins-x/environment-tekton-mole-dev, pull requests merged in 2019-04, with the labels that each got.

#3 feat: update prow chart to get job urls
  env/requirements.yaml
Labels: size/XS

#4 disable sinker as its zapping build pods, lets up limits and switch t…
  env/prow/values.yaml
  env/templates/limits.yaml
Labels: size/S

#9 add bdd serviceaccount
  env/templates/bdd-secret.yaml
Labels: approved, size/S

#11 add test bot secret
  env/templates/gh-test-secret.yaml
Labels: approved, size/S

#12 lets use the same set of annotations and labels from the old cluster
  env/templates/gh-test-secret.yaml
Labels: approved, size/XS

#13 Update to prow 0.0.484
  env/requirements.yaml
Labels: approved, size/XS

#5 fix: enable a GCS bucket for logs
  env/templates/dev-env.yaml
Labels: approved, size/XS

#14 Enabling datadog agents to collect container logs
  env/values.yaml
Labels: approved, size/XS

#15 fix: GCS storage
  env/templates/dev-env.yaml
Labels: approved, size/XS

#16 preview pipelinerunner with logrus logging
  env/prow/values.yaml
Labels: approved, size/XS

#17 fix: remove version override for prow
  env/prow/values.yaml
Labels: approved, lgtm, size/XS

#18 add core chartmuseum secret
  env/templates/core-chartmuseum-secret.yaml
Labels: approved, size/S

#19 switch from rawlingsj to to gcr.io/jenkinsxio/builder-go
  jenkins-x.yml
Labels: approved, size/XS

#25 bump prow to latest release
  env/prow/values.yaml
  env/requirements.yaml
Labels: approved, size/XS

#26 add aws bdd secret
  env/templates/bdd-aws.yaml
Labels: approved, size/S

#28 fix: switch PR build to use jx step helm build
  env/Makefile
  jenkins-x.yml
Labels: approved, lgtm, size/S

#30 bump pipeline runner to get new git clone logic
  env/prow/values.yaml
Labels: approved, size/XS

#31 Revert "bump pipeline runner to get new git clone logic"
  env/prow/values.yaml
Labels: approved, size/XS

#38 try and fix inline secrets replacement from vault
  env/jx-app-sso/values.yaml
Labels: approved, size/XS

#41 indent values using helm alias for dex
  env/jx-app-sso/values.yaml
Labels: approved, size/S

#84 switch tekton to gcs storage rather than using PVs so we can run parallel builds
  env/prow/values.yaml
  env/templates/tekton-artifact-bucket-cm.yaml
  env/templates/tekton-artifact-bucket-secret.yaml
Labels: approved, size/S

#85 ensure dex uses correct org to validate users against, also lets always create the tekton bucket secret
  env/jx-app-sso/values.yaml
  env/templates/tekton-artifact-bucket-secret.yaml
Labels: approved, size/XS
